[terra-dev-site] CVE fixes
cerner/terra-application pull request #320
Opened 2023-01-24 14:32 UTC by sugan2416

### Summary

Fixes `terra-dev-site` CVEs 

Closes #

### Deployment Link

https://terra-applic-.herokuapp.com/

### Testing

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

2023-01-24 14:38 UTC, JessieRandle commented
<!--
  1 failure:  Please include a ...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package on this PR. Looks like a CHANGELOG is missing for: 

 - terra-dev-site</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5d64cd081a5ed9f9172c0d208d7b0ec60f6bb591
</p>

2023-02-14 15:44 UTC, supreethmr commented on package.json
>      "link-parent-bin": "^1.0.0",
remove link-parent-bin

2023-02-14 15:57 UTC, sugan2416 commented on package.json
>      "link-parent-bin": "^1.0.0",
Removed https://github.com/cerner/terra-application/pull/320/commits/6727052e7e30ed056d069c432949024171d3507a

2023-02-15 05:37 UTC, saket2403 commented on packages/terra-application/src/terra-dev-site/app/components.2/ApplicationBase.app.mdx
> +!-- Consumers of ApplicationBase should review Terra's [theme aggregation](https://github.com/cerner/terra-toolkit-boneyard/blob/main/scripts/aggregate-themes/README.md) instructions to ensure the al
```suggestion
Consumers of ApplicationBase should review Terra's [theme aggregation](https://github.com/cerner/terra-toolkit-boneyard/blob/main/scripts/aggregate-themes/README.md) instructions to ensure the all theme properties are loaded appropriately.
```

2023-02-15 06:31 UTC, sugan2416 commented on packages/terra-application/src/terra-dev-site/app/components.2/ApplicationBase.app.mdx
> +!-- Consumers of ApplicationBase should review Terra's [theme aggregation](https://github.com/cerner/terra-toolkit-boneyard/blob/main/scripts/aggregate-themes/README.md) instructions to ensure the al
https://github.com/cerner/terra-application/pull/320/commits/ad798c27f4ac33ca4bced4f44443b07aa11d0cc4

2023-02-15 17:30 UTC, supreethmr approved these changes

2023-02-15 18:17 UTC, supreethmr requested changes
We have updated the props table screenshot for incorrect style value in this PR : https://github.com/cerner/terra-application/pull/319 
As you can see the 1st column ( prop names ) are expected to be displayed as bold but due to html-table changes https://github.com/cerner/terra-core/pull/3695/files#diff-1914341c0a4e12e578a435150e3253cafe5e6be59094713364fbaf116569f5e1 
[props table styles](https://github.com/cerner/terra-application/blob/02a2d1d55e19b604df8e19a36d3eae67f4417adc/packages/terra-dev-site/src/loader-components/PropsTable.module.scss#L6) were over-ridden

you need to re-generate screenshots for props-table by marking [bold style as important](https://github.com/cerner/terra-application/blob/40092103a2d936246f0eca5078ba16d7f89efc71/packages/terra-dev-site/src/loader-components/PropsTable.module.scss#L6)

2023-02-16 15:57 UTC, supreethmr approved these changes

2023-02-17 04:26 UTC, sugan2416 commented
Tested with Terra Core and Framework. Requires mdx syntax corrections.

2023-02-17 04:27 UTC, merged