[terra-application] Add theme density support to Terra Application and Dev Site
cerner/terra-application pull request #361
Opened 2023-12-18 20:27 UTC by cm9361

### Summary

**What was changed:**
The terra-application and terra-dev-site packages were updated to support theme density in preparation for the new Redwood theme.

**Why it was changed:**
The change was made because the new Redwood theme has three data densities.  The changes for this pull request allow applications to be configured to specify a density as well as properly test the density in components.

### Testing

This change was tested using:

- [X] WDIO
- [X] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details
N/A

**This PR resolves:**

UXPLATFORM-10096 

---

Thank you for contributing to Terra.
@cerner/terra

2023-12-19 21:09 UTC, nikhitasharma requested changes

2023-12-19 21:09 UTC, nikhitasharma commented on packages/terra-application/src/application-base/ApplicationBase.jsx
> +   * The name of the theme to apply to the application using terra-theme-provider.
This needs to be updated for theme density

2023-12-21 15:10 UTC, nikhitasharma approved these changes

2023-12-21 16:45 UTC, adoroshk approved these changes

2024-01-05 17:50 UTC, merged